/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.weddingplanner;

/**
 *
 * @author mannu
 */
public class NormalBooking extends javax.swing.JFrame {

    /**
     * Creates new form NormalBooking
     */
    public NormalBooking() {
        initComponents();
        setTitle("User - Normal booking");
        setResizable(true);
        setVisible(true);
        setLayout(null);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBride = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGroom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        marriageDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVenue = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGuestNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mealBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnDecoYes = new javax.swing.JRadioButton();
        btnDecoNo = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        musicBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnViewDetail = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 153, 153));
        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\mannu\\Documents\\NetBeansProjects\\weddingPlanner\\backPageLogo.png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 58, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Normal Booking");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 1, 203, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Bride Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 18, 113, -1));

        txtBride.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(txtBride, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 15, 186, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Groom's Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 50, 113, -1));

        txtGroom.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(txtGroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 47, 186, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Marriage Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 79, 113, 30));
        jPanel1.add(marriageDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 79, 186, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 102));
        jLabel5.setText("------- Choose Option -------");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 115, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Booking Charge :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 146, 132, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Rs. 75,000");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 146, 84, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Marriage Location :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 172, -1, 24));

        txtVenue.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenueActionPerformed(evt);
            }
        });
        jPanel1.add(txtVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 183, 28));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("No. of Guest :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 123, 26));

        txtGuestNo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(txtGuestNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 183, 32));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Catering :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 247, 110, 26));

        mealBox.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        mealBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select any one", "Vegetarian", "Non-Vegetarian", "Both" }));
        jPanel1.add(mealBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 183, 32));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Decoration :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 284, 118, -1));

        btnDecoYes.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnDecoYes.setForeground(new java.awt.Color(204, 0, 102));
        btnDecoYes.setText("Yes");
        jPanel1.add(btnDecoYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 63, -1));

        btnDecoNo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnDecoNo.setForeground(new java.awt.Color(204, 0, 102));
        btnDecoNo.setText("No");
        btnDecoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecoNoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDecoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 64, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Music :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 124, 30));

        musicBox.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        musicBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose your choice", "DJ", "Band", "Both" }));
        musicBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicBoxActionPerformed(evt);
            }
        });
        jPanel1.add(musicBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 183, 30));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 463, 86, 27));

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(204, 0, 102));
        btnSubmit.setText("Submit");
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 388, 110, -1));

        btnViewDetail.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnViewDetail.setForeground(new java.awt.Color(204, 0, 102));
        btnViewDetail.setText("View Details");
        jPanel1.add(btnViewDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 388, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(204, 0, 102));
        btnClear.setText("Clear");
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 388, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\mannu\\Documents\\NetBeansProjects\\weddingPlanner\\standardBook.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 39, 454, 439));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\mannu\\Documents\\NetBeansProjects\\weddingPlanner\\w1.jpg")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\mannu\\Documents\\NetBeansProjects\\weddingPlanner\\w1.jpg")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 630, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenueActionPerformed

    private void btnDecoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDecoNoActionPerformed

    private void musicBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserRequirements user= new UserRequirements();
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NormalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NormalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NormalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NormalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NormalBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JRadioButton btnDecoNo;
    private javax.swing.JRadioButton btnDecoYes;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser marriageDate;
    private javax.swing.JComboBox<String> mealBox;
    private javax.swing.JComboBox<String> musicBox;
    private javax.swing.JTextField txtBride;
    private javax.swing.JTextField txtGroom;
    private javax.swing.JTextField txtGuestNo;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
